<a href="https://colab.research.google.com/github/FelipeFlorezO/Machine_Learning/blob/main/Semana_3_ML_regresssion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML - Regression

### Importar librerias necesarias

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

sns.set_theme(style="whitegrid")

%matplotlib inline

## Motivación

Se obtuvieron diez variables iniciales, edad, sexo, índice de masa corporal, presión arterial promedio y seis mediciones de suero sanguíneo para cada uno de n = 442 pacientes con diabetes, así como la respuesta de interés, una medida cuantitativa de la progresión de la enfermedad un año después de la línea base.

Link de los datos : https://www4.stat.ncsu.edu/~boos/var.select/diabetes.tab.txt

In [ ]:
dataset="diabetes.xlsx"
diabetes= pd.read_excel(dataset)
dataraw= diabetes.values
x = dataraw[:,:-1]  # Entradas
y = dataraw[:,-1]   # Columna de salida (variable de salida) --- Output
n,d = x.shape     # Dimensión de nuestro dataset.

In [ ]:
diabetes

     AGE  SEX   BMI      BP   S1     S2    S3    S4      S5   S6    Y
0     59    2  32.1  101.00  157   93.2  38.0  4.00  4.8598   87  151
1     48    1  21.6   87.00  183  103.2  70.0  3.00  3.8918   69   75
2     72    2  30.5   93.00  156   93.6  41.0  4.00  4.6728   85  141
3     24    1  25.3   84.00  198  131.4  40.0  5.00  4.8903   89  206
4     50    1  23.0  101.00  192  125.4  52.0  4.00  4.2905   80  135
..   ...  ...   ...     ...  ...    ...   ...   ...     ...  ...  ...
437   60    2  28.2  112.00  185  113.8  42.0  4.00  4.9836   93  178
438   47    2  24.9   75.00  225  166.0  42.0  5.00  4.4427  102  104
439   60    2  24.9   99.67  162  106.6  43.0  3.77  4.1271   95  132
440   36    1  30.0   95.00  201  125.2  42.0  4.79  5.1299   85  220
441   36    1  19.6   71.00  250  133.2  97.0  3.00  4.5951   92   57

[442 rows x 11 columns]

In [ ]:
dataraw

array([[ 59.    ,   2.    ,  32.1   , ...,   4.8598,  87.    , 151.    ],
       [ 48.    ,   1.    ,  21.6   , ...,   3.8918,  69.    ,  75.    ],
       [ 72.    ,   2.    ,  30.5   , ...,   4.6728,  85.    , 141.    ],
       ...,
       [ 60.    ,   2.    ,  24.9   , ...,   4.1271,  95.    , 132.    ],
       [ 36.    ,   1.    ,  30.    , ...,   5.1299,  85.    , 220.    ],
       [ 36.    ,   1.    ,  19.6   , ...,   4.5951,  92.    ,  57.    ]])

Las primeras 10 columnas son valores predictivos numéricos

La columna 11 es una medida cuantitativa de la progresión de la enfermedad un año después del inicio


| Feature       | Description     |
| :------------- | :----------: |
| age | age in years|
| sex | sex |
| bmi | body mass index|
| bp | average blood pressure|
| s1 | tc, T-Cells (a type of white blood cells)|
| s2 | ldl, low-density lipoproteins|
| s3 | hdl, high-density lipoproteins|
| s4 | tch, thyroid stimulating hormone|
| s5 | ltg, lamotrigine|
| s6 | glu, blood sugar level|

# MISSING VALUES

## Se revisara el porcentaje de valores perdidos en cada columna

In [ ]:
diabetes.isnull().sum() / len(diabetes) * 100   # To get percentage of missing data in each column

AGE    0.0
SEX    0.0
BMI    0.0
BP     0.0
S1     0.0
S2     0.0
S3     0.0
S4     0.0
S5     0.0
S6     0.0
Y      0.0
dtype: float64

# ESTADISTICAS

## Medidas estadísticas de las variables

In [ ]:
diabetes.describe().T

,count,mean,std,min,25%,50%,75%,max
AGE,442.0,48.518100,13.109028,19.0000,38.2500,50.00000,59.0000,79.000
SEX,442.0,1.468326,0.499561,1.0000,1.0000,1.00000,2.0000,2.000
BMI,442.0,26.375792,4.418122,18.0000,23.2000,25.70000,29.2750,42.200
BP,442.0,94.647014,13.831283,62.0000,84.0000,93.00000,105.0000,133.000
S1,442.0,189.140271,34.608052,97.0000,164.2500,186.00000,209.7500,301.000
S2,442.0,115.439140,30.413081,41.6000,96.0500,113.00000,134.5000,242.400
S3,442.0,49.788462,12.934202,22.0000,40.2500,48.00000,57.7500,99.000
S4,442.0,4.070249,1.290450,2.0000,3.0000,4.00000,5.0000,9.090
S5,442.0,4.641411,0.522391,3.2581,4.2767,4.62005,4.9972,6.107
S6,442.0,91.260181,11.496335,58.0000,83.2500,91.00000,98.0000,124.000
Y,442.0,152.133484,77.093005,25.0000,87.0000,140.50000,211.5000,346.000

# ESTANDARIZACIÓN/NORMALIZACIÓN

## Nota: Cada una de estas 10 variables de características se han centrado en la media y se han escalado por la desviación estándar.

In [ ]:
from sklearn.preprocessing import StandardScaler
scaled_features = StandardScaler().fit_transform(x)
scaled_features = pd.DataFrame(data=scaled_features)
scaled_features

,0,1,2,3,4,5,6,7,8,9
0,0.800500,1.065488,1.297088,0.459841,-0.929746,-0.732065,-0.912451,-0.054499,0.418531,-0.370989
1,-0.039567,-0.938537,-1.082180,-0.553505,-0.177624,-0.402886,1.564414,-0.830301,-1.436589,-1.938479
2,1.793307,1.065488,0.934533,-0.119214,-0.958674,-0.718897,-0.680245,-0.054499,0.060156,-0.545154
3,-1.872441,-0.938537,-0.243771,-0.770650,0.256292,0.525397,-0.757647,0.721302,0.476983,-0.196823
4,0.113172,-0.938537,-0.764944,0.459841,0.082726,0.327890,0.171178,-0.054499,-0.672502,-0.980568
...,...,...,...,...,...,...,...,...,...,...
437,0.876870,1.065488,0.413360,1.256040,-0.119769,-0.053957,-0.602843,-0.054499,0.655787,0.151508
438,-0.115937,1.065488,-0.334410,-1.422086,1.037341,1.664355,-0.602843,0.721302,-0.380819,0.935254
439,0.876870,1.065488,-0.334410,0.363573,-0.785107,-0.290965,-0.525441,-0.232934,-0.985649,0.325674
440,-0.956004,-0.938537,0.821235,0.025550,0.343075,0.321306,-0.602843,0.558384,0.936163,-0.545154
441,-0.956004,-0.938537,-1.535374,-1.711613,1.760535,0.584649,3.654268,-0.830301,-0.088752,0.064426

In [ ]:
sns.pairplot(diabetes)

## Linear Regression

## Implementación

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(scaled_features, y, test_size=0.2, random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
print(f"Coefficients:\n {model.coef_.T}\n")
print(f"Score: {model.score(X_train, y_train)}")

Coefficients:
 [ -1.69095299 -11.56618382  26.76787514  14.52941617 -31.5215625
  15.42097273   1.17718013   8.10153224  34.80044394   2.04677265]

Score: 0.5539250081377072

In [ ]:
print("\t %d datos para training" %X_train.shape[0])
print("\t %d datos para testing" %X_test.shape[0])

	 353 datos para training
	 89 datos para testing

In [ ]:
%%timeit
LinearRegression().fit(X_train, y_train)

2.11 ms ± 73.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

# COMPARACIÓN VALORES REALES vs VALORES PREDICHOS

## Se visualiza que el modelo de regresión lineal no es el mejor para predecir el target.

In [ ]:
y_pred = model.predict(X_train)
line = np.arange(0, y_train.max(), 0.1)

fig, ax = plt.subplots(figsize=(6.5, 6.5))
sns.scatterplot(
    x = y_train,
    y = y_pred,
    ax = ax
)
ax.axis("equal")
ax.set_xlabel("y_true")
ax.set_ylabel("y_pred")
ax.set_title("Prediction vs True Values")
sns.lineplot(x=line, y=line, color="red", ax=ax)
fig.show()

# VALIDACIÓN DEL MODELO

## Se probará el modelo con los datos de testing

In [ ]:
# Realizar predicción
y_train_predict= model.predict(X_train) # Con los datos de entrenamiento.
y_test_predict= model.predict(X_test)  # Con los datos de prueba.

# Evaluar los scores
error_train= mean_squared_error(y_train_predict, y_train)
print("Error en training: %s" % round(error_train,2))
error_test= mean_squared_error(y_test_predict, y_test)
print("Error en testing: %s" % round(error_test,2))

Error en training: 2734.75
Error en testing: 3424.26